### ISSUE TITLE
Grant access to discord rich present named pipe

### ISSUE THREAD

**Issue by modmuss50** [FabricMC/fabric-sandbox#16]
To support mods that use the discord RPC SDK we should grant access to the `\\\\?\\pipe\\discord-ipc-0` (0-9) named pipe.

See:
- https://github.com/discord/discord-rpc/blob/master/documentation/hard-mode.md
- https://github.com/discord/discord-rpc/blob/master/src/connection_win.cpp#L35C26-L35C52

**Comment by hypherionmc** [comment]
There's also these two paths on linux, for snap and flatpak versions of discord. Some mods like CraftPresence also use this, if it fails to use the official paths

`String[] unixFolderPaths = {"/snap.discord", "/app/com.discordapp.Discord"};`

EDIT: Just realized it's a windows project..... Duh moment there. My bad

**Comment by CDAGaming** [comment]
Bumped!
Related data: https://github.com/CDAGaming/DiscordIPC/blob/master/src/main/java/com/jagrosh/discordipc/entities/pipe/Pipe.java#L41

(CraftPresence uses a fork of DiscordIPC, and covers quite a few paths)
